WIP. Everything hardcoded just to get to install 0.13.16.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -ex
+
 install_sbt() {
   local install_type=$1
   local version=$2
@@ -12,20 +14,20 @@ install_sbt() {
     exit 1
   fi
 
-  if [ "version" != "${install_type}" ]; then
-    echo "The asdf-sbt plugin only supports installing official "
-    echo "binary releases as built by the Scala team."
-    # echo "If you want to install another version from source, see: "
-    # echo "https://github.com/scala/scala/"
-    exit 1
-  fi
+#  if [ "version" != "${install_type}" ]; then
+#    echo "The asdf-sbt plugin only supports installing official "
+#    echo "binary releases as built by the Scala team."
+#    # echo "If you want to install another version from source, see: "
+#    # echo "https://github.com/scala/scala/"
+#    exit 1
+#  fi
 
-  local url_download="$(get_download_url $install_type $version)"
+  local url_download="https://cocl.us/sbt-0.13.16.tgz"
 
-  if [ "Distribution file not found. Exiting" == "${url_download}" ]; then
-    echo "The version specified was not found. Exiting"
-    exit 1
-  fi
+#  if [ "Distribution file not found. Exiting" == "${url_download}" ]; then
+#    echo "The version specified was not found. Exiting"
+#    exit 1
+#  fi
 
   if [ "$TMPDIR" = "" ]; then
     local tmp_download_dir=$(mktemp -d)
@@ -41,20 +43,11 @@ install_sbt() {
   )
 }
 
-download_source_file() {
-  local install_type=$1
-  local version=$2
-  local download_path=$3
-  local download_url=$(get_download_url $install_type $version)
-
-  curl -Lo $download_path -C - $download_url
-}
-
 download_source_file_url() {
   local url=$1
   local download_path=$2
 
-  curl -Lo $download_path -C - $url
+  curl -Lo $download_path $url
 }
 get_download_file_path() {
   local install_type=$1
@@ -67,24 +60,16 @@ get_download_file_path() {
 }
 
 get_url_status() {
-  local url="$1"
-  local status="$(curl -s -I -L "$url" | grep 'HTTP/1.1' | awk '{print $2}' | tail -n 1)"
+  local url="https://cocl.us/sbt-0.13.16.tgz"
+  local status="$(curl -I -L "$url")"
 
   echo "$status"
 }
 
 get_download_url() {
   local install_type=$1
-  local version=$2
-  local baseurl_bintray="https://dl.bintray.com/sbt/native-packages/sbt/${version}/sbt-${version}.tgz"
-
-
-  if [[ "x200" == "x$(get_url_status "$baseurl_bintray")" ]]; then
-    echo "$baseurl_bintray"
-  else
-    echo "Distribution file not found. Exiting"
-    exit 1
-  fi
+  local version="0.13.16"
+  local baseurl_bintray="https://cocl.us/sbt-0.13.16.tgz"
 }
 
-install_sbt $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
+install_sbt "0.13.16" "0.13.16" /Users/vpeurala/.asdf
